version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      # install dependencies
      - run:
          name: install dependencies
          command: npm install
      - run:
          working_directory: ~/src/server
          name: test
          command: npm run test
workflows:
  test_my_app:
    jobs:
      - build_and_test
